Jonnitto:
  PrettyEmbedAudio:
    defaults:
      # If true, the browser will offer controls to allow the user to control
      # audio playback, including volume, seeking, and pause/resume playback.
      controls: true

      # If true, the browser will automatically seek back
      # to the start upon reaching the end of the audio.
      loop: false

      # This enumerated attribute is intended to provide a hint to the browser about what
      # the author thinks will lead to the best user experience with regards to what content
      # is loaded before the audio is played. It may have one of the following values:
      #  - none       Indicates that the audio should not be preloaded.
      #  - metadata   Indicates that the browser should load only metadata when the page loads
      #  - auto       Indicates that the whole audio file can be downloaded, even if the user is not expected to use it
      preload: metadata

      # Whether the audio plays inline on supported mobile devices.
      # Note that if set to false it does not imply that the audio will always be played in fullscreen.
      playsinline: true

      # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-crossorigin
      # anonymous || use-credentials || true || false
      crossorigin: false
