Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PrettyEmbedAudio:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PrettyEmbedAudio: true
